### ISSUE TITLE
Error resolving dns while sending admin mail

### ISSUE THREAD

**Issue by UkeHa** [bitwarden/web#373]
When i'm trying to send an admin email to generate a login i get an error 500 from the server. This worked fine in previous versions (broken for me in at least in 1.30/1.30.1). I've updated the images to the latest version but still get the same error (without changing anything else on the server).

Ping to the Exchange-Server set up in the global-override file works on the machine, if i put in our local domain (e.g. myexchange.Contoso.local)

```
2019-04-03 09:12:37.775 +00:00 [Error] Connection id ""0HLLO2I14RQOH"", Request id ""0HLLO2I14RQOH:00000001"": An unhandled exception was thrown by the application.
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DnsCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /home/appveyor/projects/server/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 72
   at Bit.Core.Services.HandlebarsMailService.SendPasswordlessSignInAsync(String returnUrl, String token, String email) in /home/appveyor/projects/server/src/Core/Services/Implementations/HandlebarsMailServ$
   at Bit.Core.Identity.PasswordlessSignInManager`1.PasswordlessSignInAsync(String email, String returnUrl) in /home/appveyor/projects/server/src/Core/Identity/PasswordlessSignInManager.cs:line 41
   at Bit.Admin.Controllers.LoginController.Index(LoginModel model) in /home/appveyor/projects/server/src/Admin/Controllers/LoginController.cs:line 41
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by kspearrin** [comment]
Are you able to ping the machine from within the actual docker container, such as `bitwarden-admin`?

**Comment by Zoba273** [comment]
Ping from within bitwarden-admin results in "ping: myexchange: Temporary failure in name resolution"
pinging with the contoso.local suffix results in a working ping

**Comment by kspearrin** [comment]
I am a bit confused. So it is working, or not?

**Comment by Zoba273** [comment]
As am I. It doesn't work by name but with a fully qualified name it does work. And it worked before updates (haven't look into it a couple of weeks, so can't quite put down when it stopped working). Pinging the IP works flawlessly as well
![image](https://user-images.githubusercontent.com/2254304/55485492-d5f92180-562a-11e9-8beb-b62a4f4b8c00.png)

**Comment by kspearrin** [comment]
We changed mail libraries in the last update, so its possible some requirements for the FQDN changed with that. Can you just use the FQDN or IP now?

**Comment by Zoba273** [comment]
Sadly no. It seems to ignore the FQDN. Something is fishy here. Running dig on the ip doesn't get answered by the DC of the Active Directory. Instead it's been replied to by the firewall (?)

**Comment by kspearrin** [comment]
Is it possible to try disabling the firewall temporarily to see if that allows it to go through?

**Comment by Zoba273** [comment]
No that's not possible. Running dig on the IP doesn't result in a response but the authority section differs from the domain controller:

![image](https://user-images.githubusercontent.com/2254304/55556644-59c51380-56e8-11e9-9586-5162d41e5721.png)

**Comment by Zoba273** [comment]
@kspearrin i've added the exchange in the admin docker /etc/hosts file and the problem persists. I still get an error in the dns host resolution.

**Comment by kspearrin** [comment]
You need to figure out the DNS issues with Docker first. I don't know how your network is configured, so it's hard to say. Try creating just a standard [Debian Docker container](https://hub.docker.com/_/debian) that you can use to troubleshoot the problem. If you find a solution, it should fix the problems you are also having with Bitwarden containers.

**Comment by Zoba273** [comment]
Okay, i've figured out the issue with the ping but the problem persists. The problem was that the domain to search was entered into netplan instead of being configured with systemd so it only affected the specific adapter. When it comes to dig, the default behaviour of dig is to disregard the search/domain. You can enable it specifically with the +search parameter and then dig works as intended. After these changes i can now ping from within the docker containers as well as from the host. The problem is still exactly the same as before; i still think this is a bug, as it worked prior to your change and using the full qualified domain name worked just fine as it resolved the entire address - as it should. Even using an IP instead of the domain name should affect the results, as it shouldn't need to resolve anything. The problem is, that this is essentially a lock on the admin interface. I'd be good to have something like the gmail backup codes that allow for a single use.

**Comment by kspearrin** [comment]
Can you share your redacted mail env variables?

**Comment by Zoba273** [comment]
`globalSettings__baseServiceUri__vault=https://my-bitwarden
globalSettings__baseServiceUri__api=https://my-bitwarden/api
globalSettings__baseServiceUri__identity=https://my-bitwarden/identity
globalSettings__baseServiceUri__admin=https://my-bitwarden/admin
globalSettings__baseServiceUri__notifications=https://my-bitwarden/notifications
globalSettings__sqlServer__connectionString="Data Source=tcp:mssql,1433;Initial Catalog=vault;Persist Security Info=False;User ID=user;password;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True"
globalSettings__identityServer__certificatePassword=thisismypassword
globalSettings__attachment__baseDirectory=/etc/bitwarden/core/attachments
globalSettings__attachment__baseUrl=https://my-bitwarden/attachments
globalSettings__dataProtection__directory=/etc/bitwarden/core/aspnet-dataprotection
globalSettings__logDirectory=/etc/bitwarden/logs
globalSettings__licenseDirectory=/etc/bitwarden/core/licenses
globalSettings__internalIdentityKey=myinternalID
globalSettings__duo__aKey=duoKey
globalSettings__installation__id=installID
globalSettings__installation__key=installKey
globalSettings__yubico__clientId=REPLACE
globalSettings__yubico__key=REPLACE
globalSettings__mail__replyToEmail=no-reply@my-bitwarden
globalSettings__mail__smtp__host=my-exchange
globalSettings__mail__smtp__port=25
globalSettings__mail__smtp__ssl=false
globalSettings__mail__smtp__username=username
globalSettings__mail__smtp__password=password
globalSettings__disableUserRegistration=false
adminSettings__admins=admin@mydomain.com
globalSettings__mail__smtp__useDefaultCredentials=false`

**Comment by kspearrin** [comment]
Thanks. Are you expecting to connect over StartTLS or just unencrypted?

**Comment by Zoba273** [comment]
it's unencrypted to the exchange

**Comment by UkeHa** [comment]
Any news?

**Comment by kspearrin** [comment]
No, sorry, I am out of ideas at this point. It seems network related. I do not know why it would have worked in a previous version. We switched to a new mail library in this version (https://github.com/jstedfast/MailKit), which seems to have onset the issue, but I am not sure why that is affecting connectivity.

**Comment by UkeHa** [comment]
That doesn't really explain why it worked beforehand. And after dealing with the problem of the image requiring the FQDN and figuring out that dig runs in a +nosearch mode on default, i think the problem lies in the change of the MailKit-Version. I'll open an issue with them too, to figure out if it's a problem on their side. Which version/libary did you use before the change?

**Comment by kspearrin** [comment]
We used .NET `SmtpClient` beforehand, but that has been deprecated by Microsoft, which is why we switched.

**Comment by UkeHa** [comment]
Okay,
i changed the unencrypted port to 587 and kept ssl on false. Now i get a different error - yay progress.
That exchange runs with a self-signed certificate. Could i make things work if i add the cert to /bwdata/ca-certificates?

```
2019-04-30 12:47:58.310 +00:00 [Error] Connection id ""0HLMDD86U0CDL"", Request id ""0HLMDD86U0CDL:00000001"": An unhandled excepti$
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions. ---> System.Security.Auth$
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDisp$
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 prom$
--- End of stack trace from previous location where exception was thrown ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationT$
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationT$
   at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /home/appveyor/projects/server/src/Co$
   at Bit.Core.Services.HandlebarsMailService.SendPasswordlessSignInAsync(String returnUrl, String token, String email) in /home/ap$
   at Bit.Core.Identity.PasswordlessSignInManager`1.PasswordlessSignInAsync(String email, String returnUrl) in /home/appveyor/proje$
   at Bit.Admin.Controllers.LoginController.Index(LoginModel model) in /home/appveyor/projects/server/src/Admin/Controllers/LoginCo$
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, Ob$
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by kspearrin** [comment]
You should be able to add any self-signed certs to ./bwdata/ca-certificates to be added to the trusted store in the containers.
